# This file was generated by GoReleaser. DO NOT EDIT.
cask "keeper" do
  version "0.0.24"

  on_macos do
    on_intel do
      sha256 "df4c005cf02c713c05a551770536920f59cd882d212d4c61ac6295f1757abd98"
      url "https://github.com/dragpass/keeper/releases/download/v#{version}/dragpass-keeper_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e1aafad68cfd01e19759939f78e7c01a2c822ef34a38c64bf704d8a95831080d"
      url "https://github.com/dragpass/keeper/releases/download/v#{version}/dragpass-keeper_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "keeper"
  desc "Native key-custody helper for the DragPass Chrome Extension"
  homepage "https://github.com/dragpass/keeper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dragpass-keeper"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dragpass-keeper"]
      manifest_dir = File.expand_path("~/Library/Application Support/Google/Chrome/NativeMessagingHosts")
      FileUtils.mkdir_p manifest_dir
      manifest = <<~JSON
        {
          "name": "com.dragpass.keeper",
          "description": "DragPass Device Key Storage",
          "path": "#{HOMEBREW_PREFIX}/bin/dragpass-keeper",
          "type": "stdio",
          "allowed_origins": [
            "chrome-extension://cmgjlocmnppfpknaipdfodjhbplnhimk/"
          ]
        }
      JSON
      File.write(File.join(manifest_dir, "com.dragpass.keeper.json"), manifest)
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The Chrome Native Messaging manifest was installed to:
      ~/Library/Application Support/Google/Chrome/NativeMessagingHosts/com.dragpass.keeper.json
    Restart Chrome (or disable and re-enable the DragPass extension) to pick it up.
  EOS
end
