# This file was generated by GoReleaser. DO NOT EDIT.
cask "keeper" do
  version "0.0.7"

  on_macos do
    on_intel do
      sha256 "c94c6c17568185375a6f3d7cc7c04a9a0b38e3b87d1320ed9cadbe3092ee75a8"
      url "https://github.com/dragpass/keeper/releases/download/v#{version}/dragpass-keeper_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1b7bdf726acfebba166878e5a0dd77c956ae8046784afb8a7c45e6240eddd1ba"
      url "https://github.com/dragpass/keeper/releases/download/v#{version}/dragpass-keeper_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "keeper"
  desc "Native key-custody helper for the DragPass Chrome Extension"
  homepage "https://github.com/dragpass/keeper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dragpass-keeper"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dragpass-keeper"]
      manifest_dir = File.expand_path("~/Library/Application Support/Google/Chrome/NativeMessagingHosts")
      FileUtils.mkdir_p manifest_dir
      manifest = <<~JSON
        {
          "name": "com.dragpass.keeper",
          "description": "DragPass Device Key Storage",
          "path": "#{HOMEBREW_PREFIX}/bin/dragpass-keeper",
          "type": "stdio",
          "allowed_origins": [
            "chrome-extension://cmgjlocmnppfpknaipdfodjhbplnhimk/"
          ]
        }
      JSON
      File.write(File.join(manifest_dir, "com.dragpass.keeper.json"), manifest)
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The Chrome Native Messaging manifest was installed to:
      ~/Library/Application Support/Google/Chrome/NativeMessagingHosts/com.dragpass.keeper.json
    Restart Chrome (or disable and re-enable the DragPass extension) to pick it up.
  EOS
end
