# This file was generated by GoReleaser. DO NOT EDIT.
cask "keeper" do
  version "0.0.28"

  on_macos do
    on_arm do
      sha256 "e222b565c0b9a208b9cb64c49dabd5e7d677f4566e060dbd2abc7b5a53d27a50"
      url "https://github.com/dragpass/keeper/releases/download/v#{version}/dragpass-keeper_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e7ff6a3ee1bb7dc6e41d8941a971f30bdc95ec07ae3c086a64fc3359cf9d8f40"
      url "https://github.com/dragpass/keeper/releases/download/v#{version}/dragpass-keeper_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "keeper"
  desc "Native key-custody helper for the DragPass Chrome Extension"
  homepage "https://github.com/dragpass/keeper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dragpass-keeper"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/dragpass-keeper"]
      manifest_dir = File.expand_path("~/Library/Application Support/Google/Chrome/NativeMessagingHosts")
      FileUtils.mkdir_p manifest_dir
      manifest = <<~JSON
        {
          "name": "com.dragpass.keeper",
          "description": "DragPass Device Key Storage",
          "path": "#{HOMEBREW_PREFIX}/bin/dragpass-keeper",
          "type": "stdio",
          "allowed_origins": [
            "chrome-extension://cmgjlocmnppfpknaipdfodjhbplnhimk/"
          ]
        }
      JSON
      File.write(File.join(manifest_dir, "com.dragpass.keeper.json"), manifest)
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The Chrome Native Messaging manifest was installed to:
      ~/Library/Application Support/Google/Chrome/NativeMessagingHosts/com.dragpass.keeper.json
    Restart Chrome (or disable and re-enable the DragPass extension) to pick it up.
  EOS
end
