# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keeper < Formula
  desc "Native key-custody helper for the DragPass Chrome Extension"
  homepage "https://github.com/dragpass/keeper"
  version "0.0.1"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/dragpass/keeper/releases/download/v0.0.1/dragpass-keeper_0.0.1_darwin_amd64.tar.gz"
    sha256 "335f092acc40232e92837d6de0975c65e63a993d4b28690411fcf7129288319e"

    define_method(:install) do
      bin.install "dragpass-keeper"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/dragpass/keeper/releases/download/v0.0.1/dragpass-keeper_0.0.1_darwin_arm64.tar.gz"
    sha256 "d16ac7dfb1638a6e72d6b1439249e8eea0f590c24d3d09be2624adc8d792271f"

    define_method(:install) do
      bin.install "dragpass-keeper"
    end
  end

  def post_install
    manifest_dir = File.expand_path("~/Library/Application Support/Google/Chrome/NativeMessagingHosts")
    FileUtils.mkdir_p manifest_dir
    manifest = <<~JSON
      {
        "name": "com.dragpass.keeper",
        "description": "DragPass Device Key Storage",
        "path": "#{opt_bin}/dragpass-keeper",
        "type": "stdio",
        "allowed_origins": [
          "chrome-extension://cmgjlocmnppfpknaipdfodjhbplnhimk/"
        ]
      }
    JSON
    File.write(File.join(manifest_dir, "com.dragpass.keeper.json"), manifest)
  end

  def caveats
    <<~EOS
      The Chrome Native Messaging manifest was installed to:
        ~/Library/Application Support/Google/Chrome/NativeMessagingHosts/com.dragpass.keeper.json
      Restart Chrome (or disable and re-enable the DragPass extension) to pick it up.
    EOS
  end
end
